apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-a-deployment
  labels:
    app: go-service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service-a-deployment
  template:
    metadata:
      labels:
        app: go-service-a-deployment
    spec:
      containers:
      - name: service-a
        image: observability/go-service-a:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: OTEL_COLLECTOR_ENDPOINT
          value: otel-collector.olly.svc:4318
        - name: SVC_B_URI
          value: http://b-service.otel-demo
        - name: PORT
          value: '80'
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /hello-a
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
