apiVersion: v1
kind: Service
metadata:
  name: b-service
  labels:
    job: go-api
    app: b-service
spec:
  type: ClusterIP
  ports:
  - name: b-service-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-service-b-deployment
